---
- name: 🎯 Le rôle {{ role_name }} démarre
  debug:
    msg: "Le rôle {{ role_name }} a bien été inclus"

- name: Ajouter la clé GPG de Trivy
  ansible.builtin.shell: |
    apt-get install -y wget apt-transport-https gnupg lsb-release
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor -o /usr/share/keyrings/trivy-archive-keyring.gpg
  args:
    executable: /bin/bash

- name: Ajouter le dépôt Trivy (forcé à jammy)
  ansible.builtin.shell: |
    echo "deb [signed-by=/usr/share/keyrings/trivy-archive-keyring.gpg] https://aquasecurity.github.io/trivy-repo/deb jammy main" | sudo tee /etc/apt/sources.list.d/trivy.list
  args:
    executable: /bin/bash

- name: Installer Trivy
  ansible.builtin.apt:
    name: trivy
    state: present
    update_cache: yes
