apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 # L'adresse de Prometheus à l'intérieur du réseau Docker
    isDefault: true
    access: proxy
    editable: true