name: Autodeploy

on:
  push:
    branches: [ main, cicd ]  # Déclenchement sur main et cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🛠️ Installer Ansible et Python
        run: |
          sudo apt update
          sudo apt install -y ansible python3

      - name: 🔐 Injecter la clé SSH privée
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking=no" >> ~/.ssh/config

      - name: 🧾 Créer le fichier inventory.ini
        run: |
          echo "[webserver]" > ansible/inventory.ini
          echo "${{ secrets.TARGET_HOST }} ansible_user=${{ secrets.TARGET_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_python_interpreter=/usr/bin/python3" >> ansible/inventory.ini

      - name: 🚀 Lancer le déploiement Ansible
        run: |
          cd ansible
          bash deploy.sh
